### ISSUE TITLE
проект запускается?

### ISSUE THREAD

**Issue by anatoliykant** [trykovyura/roskachestvo-ios#25]
Как запустить проект?
кажется чего-то не хватает...

**Comment by trykovyura** [comment]
Какие ошибки пишет? 
Прогнал сейчас с 0 проект. Были ошибки swiftlint - исправил в develop.

По Readme пробегись еще разок:

- Установить brew
- brew install rswift
- brew install swiftlint
- Установить Ruby
- gem install bundler
- bundle install
- bundle exec fastlane install_plugins
- bundle exec fastlane prepare
- Запустить RK.xcodeproj
